### ISSUE TITLE
Incompatible types. Found: 'cucumber.api.CucumberOptions', required: 'courgette.api.CucumberOptions'

### ISSUE THREAD

**Issue by Rodriguitos** [prashant-ramcharan/courgette-jvm#189]
Hi there:

I try to make run the Courgette Runner and when I use the import
cucumber.api.CucumberOptions;
It displays the next error:
Incompatible types. Found: 'cucumber.api.CucumberOptions', required: 'courgette.api.CucumberOptions'

And when I use the import 
courgette.api.CucumberOptions;

I face the next error:

Exception in thread "main" java.lang.NoClassDefFoundError: io/cucumber/core/snippets/SnippetType
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at sun.reflect.annotation.AnnotationType$1.run(AnnotationType.java:112)
	at sun.reflect.annotation.AnnotationType$1.run(AnnotationType.java:109)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.reflect.annotation.AnnotationType.<init>(AnnotationType.java:109)
	at sun.reflect.annotation.AnnotationType.getInstance(AnnotationType.java:85)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:266)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation(AnnotationParser.java:226)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:352)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:286)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
	at java.lang.Class.createAnnotationData(Class.java:3521)
	at java.lang.Class.annotationData(Class.java:3510)
	at java.lang.Class.getAnnotation(Class.java:3415)
	at com.intellij.junit4.JUnit4TestRunnerUtil.buildRequest(JUnit4TestRunnerUtil.java:219)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:46)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.lang.ClassNotFoundException: io.cucumber.core.snippets.SnippetType

**Comment by prashant-ramcharan** [comment]
Hello,

Please remove all other cucumber dependencies from your `pom.xml` or `build.gradle`

You just need to have the Courgette dependency.

If you still have issues, share your `pom.xml` or `build.gradle` and I'll advise further.

**Comment by Rodriguitos** [comment]
Hi Prashant:

I remove all the Cucumber dependencies, but now I'm facing the next error:

-Djava.endorsed.dirs=/Library/Java/JavaVirtualMachines/jdk1.8.0_221.jdk/Contents/Home/jre/lib/endorsed is not supported. Endorsed standards and standalone APIs
in modular form will be supported via the concept of upgradeable modules.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
courgette.runtime.CourgetteException: java.io.FileNotFoundException: target/courgette/courgette-report/data/report.json (No such file or directory)
	at courgette.runtime.report.JsonReportParser.getReportFeatures(JsonReportParser.java:65)
	at courgette.runtime.CourgetteRunner.createCourgetteReport(CourgetteRunner.java:160)
	at courgette.api.junit.Courgette.run(Courgette.java:55)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.io.FileNotFoundException: target/courgette/courgette-report/data/report.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at courgette.runtime.report.JsonReportParser.parseJsonReport(JsonReportParser.java:72)
	at courgette.runtime.report.JsonReportParser.getReportFeatures(JsonReportParser.java:63)
	... 7 more

Process finished with exit code 254

courgette.runtime.CourgetteTestFailureException: Please refer to Courgette / Cucumber report for more info.

**Comment by prashant-ramcharan** [comment]
Hello,

As you are using Java 8, in you `build.gradle` ensure that you are **not** removing the `java.endorsed.dirs` libs.

It should look like this:

````gradle
tasks.withType(Test) {
    systemProperties = System.getProperties()
}

task testSuite(type: Test) {
    include '**/YourTestSuite.class'
    outputs.upToDateWhen { false }
}
````

**Comment by Rodriguitos** [comment]
Hi Prashant:

Actually I'm using Maven, not Gradle.

This is my POM (Plugin):

<profiles>
        <profile>
            <id>JUnit_CourgetteReports</id>
                <build>
                    <plugins>
                        <plugin>
                            <groupId>org.apache.maven.plugins</groupId>
                            <artifactId>maven-surefire-plugin</artifactId>
                            <version>2.22.0</version>
                            <configuration>
                                <parallel>methods</parallel>
                                <threadCount>1</threadCount>
                                <testFailureIgnore>true</testFailureIgnore>
                                <redirectTestOutputToFile>true</redirectTestOutputToFile>
                                <includes>
                                    <include>**/runners/TestJunitCourgette.class</include>
                                </includes>
                            </configuration>
                        </plugin>
                    </plugins>
                </build>
        </profile>

**Comment by prashant-ramcharan** [comment]
I assume that the tests run fine (_**using the Courgette runner**_) when running as a JUnit test? 

This seems to be a maven surefire issue with **Java 8.** 

I'd imagine this would run fine with maven surefire and Java 9 upwards.

**Comment by prashant-ramcharan** [comment]
@Rodriguitos What version of Java do you have set on your system? `java -version`

I tried with the example project here and it works fine when I set the Java version to Java 8 in my `bash_profile`.

https://github.com/prashant-ramcharan/courgette-jvm-maven-example

Try the above and see if it's working for you.

**Comment by Rodriguitos** [comment]
Hi Prashant: 
My java version is:  1.8.0_221 (Included in my bash profile)
And I have the next error:

-Djava.endorsed.dirs=/Library/Java/JavaVirtualMachines/jdk1.8.0_221.jdk/Contents/Home/jre/lib/endorsed is not supported. Endorsed standards and standalone APIs
in modular form will be supported via the concept of upgradeable modules.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
courgette.runtime.CourgetteException: java.io.FileNotFoundException: target/courgette/courgette-report/data/report.json (No such file or directory)
	at courgette.runtime.report.JsonReportParser.getReportFeatures(JsonReportParser.java:65)
	at courgette.runtime.CourgetteRunner.createCourgetteReport(CourgetteRunner.java:160)
	at courgette.api.junit.Courgette.run(Courgette.java:55)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.io.FileNotFoundException: target/courgette/courgette-report/data/report.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at courgette.runtime.report.JsonReportParser.parseJsonReport(JsonReportParser.java:72)
	at courgette.runtime.report.JsonReportParser.getReportFeatures(JsonReportParser.java:63)
	... 7 more

Process finished with exit code 254

**Comment by prashant-ramcharan** [comment]
Hello,

Can you try running it from the command line and not IntelliJ?

Also, did you try running the example project I referenced above?

**Comment by Rodriguitos** [comment]
Hi:
Already don

When I try to run it from IntelliJ this is the message:

courgette.runtime.CourgetteException: java.io.FileNotFoundException: build/courgette-report/data/report.json (No such file or directory)
	at courgette.runtime.report.JsonReportParser.getReportFeatures(JsonReportParser.java:65)
	at courgette.runtime.CourgetteRunner.createCourgetteReport(CourgetteRunner.java:153)
	at courgette.api.junit.Courgette.run(Courgette.java:55)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.io.FileNotFoundException: build/courgette-report/data/report.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at courgette.runtime.report.JsonReportParser.parseJsonReport(JsonReportParser.java:72)
	at courgette.runtime.report.JsonReportParser.getReportFeatures(JsonReportParser.java:63)
	... 7 more

Process finished with exit code 254

courgette.runtime.CourgetteTestFailureException: Please refer to Courgette / Cucumber report for more info.

By the way this is my runner:

`import courgette.api.CourgetteOptions;
import courgette.api.CourgetteRunLevel;
import courgette.api.CucumberOptions;
import courgette.api.junit.Courgette;
import org.junit.runner.RunWith;


@RunWith(Courgette.class)
@CourgetteOptions(
        threads = 1,
        runLevel = CourgetteRunLevel.SCENARIO,
        rerunFailedScenarios = true,
        rerunAttempts = 1,
        showTestOutput = true,
        reportTargetDir = "target/courgette",
        cucumberOptions = @CucumberOptions(
                features = "src/test/resources/features",
                glue = {"stepdefs", "properties", "src/main/java/properties", "drivers", "src/main/java/drivers"},
                tags = {"@test"},
                plugin = {
                        "pretty",
                        "json:target/courgette/courgette-report/data/cucumber.json",
                        "html:target/courgette/courgette-report/data/cucumber.html",
                        "junit:target/courgette/courgette-report/data/cucumber.xml"},
                strict = true
        ))

public class TestJunitCourgette {
}`

**Comment by prashant-ramcharan** [comment]
What version of Courgette are you using?

**Comment by prashant-ramcharan** [comment]
Can you update your runner to match the below and try again?

````java
@RunWith(Courgette.class)
@CourgetteOptions(
        threads = 1,
        runLevel = CourgetteRunLevel.SCENARIO,
        rerunFailedScenarios = true,
        rerunAttempts = 1,
        showTestOutput = true,
        reportTargetDir = "target",
        cucumberOptions = @CucumberOptions(
                features = "src/test/resources/features",
                glue = {"stepdefs", "properties", "src/main/java/properties", "drivers", "src/main/java/drivers"},
                tags = {"@test"},
                plugin = {
                        "pretty",
                        "json:target/cucumber-report/cucumber.json",
                        "html:target/cucumber-report/cucumber.html",
                        "junit:target/cucumber-report/cucumber.xml"},
                strict = true
        ))
public class TestJunitCourgette {
}
````

**Comment by Rodriguitos** [comment]
Done, but I'm facing the same issue.
I don't know if this is related with the error.
```

-Djava.endorsed.dirs=/Library/Java/JavaVirtualMachines/jdk1.8.0_221.jdk/Contents/Home/jre/lib/endorsed is not supported. Endorsed standards and standalone APIs
in modular form will be supported via the concept of upgradeable modules.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Unable to create the Courgette Html Report -> java.io.FileNotFoundException: target/courgette-report/data/report.json (No such file or directory)
courgette.runtime.CourgetteTestFailureException: There were failing tests. Refer to the Courgette html report for more details.

Process finished with exit code 254

**Comment by prashant-ramcharan** [comment]
Please advise on the following:

1. What version of Courgette are you using?
2. What version of IntelliJ are you using?
3. What other versions of Java do you have installed in your machine?
4. Does the tests run fine from Maven / terminal?

 I'm **unable** to reproduce this error with this https://github.com/prashant-ramcharan/courgette-jvm-maven-example

If you can provide a demo project that I can reproduce this with then that would be great!

**Comment by Rodriguitos** [comment]
Hi Prashant:

Courgette version: 3.3.0
IntelliJ version: 2020.1 Community Version
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

I run the tests from IntelliJ runs
I cannot run the test with this runner (I'm able to run them with a simple runner)

**Comment by Rodriguitos** [comment]
Hey, I do it!!!

After disable and enable the Maven plugins I did it!!!

Thanks for all Prashant!!!

One last thing: Is there a way to put a timestamp in the report for avoid overwrite the reports?

**Comment by prashant-ramcharan** [comment]
That's great!

There's no way to currently set the timestamp for the filename. However, you can create the courgette report directory with the timestamp.

Example:

In your maven surefire plugin add the `argLine` setting the `courgette.reportTargetDir` which will create a time stamped directory in your `target` folder.

Example:
````xml
<plugin>
     <groupId>org.apache.maven.plugins</groupId>
     ...
     <configuration>
        <argLine>-Dcourgette.reportTargetDir=target/${maven.build.timestamp}</argLine>
     </configuration>
     ...
</plugin>

**Comment by Rodriguitos** [comment]
Hi: That argline is not working.

**Comment by prashant-ramcharan** [comment]
It works perfectly for me :)

https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#argLine

**Comment by prashant-ramcharan** [comment]
> One last thing: Is there a way to put a timestamp in the report for avoid overwrite the reports?

Other than the option above, Courgette does not currently support this. 

I’d imagine you CI system would archive the reports for each build so your reports shouldn’t get overridden anyway.

**Comment by Rodriguitos** [comment]
Thanks a lot Prashant!!!
I proceed to close this issue.
