### ISSUE TITLE
Getting number format exception for reports

### ISSUE THREAD

**Issue by nandajaga** [prashant-ramcharan/courgette-jvm#209]
@prashant-ramcharan  - when the tests are running in parallel for a long time(~40min), some times the reports are not generating either a courgette report or extent report. could you please help if am missing something. Am using the courgette runner class and version 4.6.2
 
Below is the execution error coming

**For input string: "1,300.065"
java.lang.NumberFormatException: For input string: "1,300.065"**
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(Double.java:538)
	at courgette.runtime.CourgetteReporter.formatXmlReport(CourgetteReporter.java:125)
	at courgette.runtime.CourgetteReporter.createReport(CourgetteReporter.java:87)
	at courgette.runtime.CourgetteRunner.lambda$createReport$2(CourgetteRunner.java:135)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at courgette.runtime.CourgetteRunner.createReport(CourgetteRunner.java:132)
	at courgette.api.junit.Courgette.run(Courgette.java:54)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy3.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by prashant-ramcharan** [comment]
Thanks for reporting @nandajaga 

I will provide a fix.

**Comment by prashant-ramcharan** [comment]
For now, to bypass this issue you can remove the `junit:build/.../cucumber.xml` Cucumber option plugin from your runner.

**Comment by nandajaga** [comment]
Thank you so much for the quick response @prashant-ramcharan

**Comment by prashant-ramcharan** [comment]
@nandajaga The fix is now released in version `5.3.0`

**Comment by nandajaga** [comment]
sure, Thank you @prashant-ramcharan 👍
