### ISSUE TITLE
Trying to migrate from standard cucumber (with spring integration) to courgette causes weird errors

### ISSUE THREAD

**Issue by sheinbergon** [prashant-ramcharan/courgette-jvm#221]
Hello

I have a working test setup using Junit5 and Cucumber JVM/Spring

When changing my cucumber runner from:

```java

@RunWith(Cucumber.class)
@CucumberOptions(
        monochrome = true,
        features = "src/test/resources/features/",
        glue = "some.package")
public class CucumberRunner {
}
```

To

```java
@RunWith(Courgette.class)
@CourgetteOptions(
        threads = 2,
        runLevel = CourgetteRunLevel.FEATURE,
        rerunFailedScenarios = true,
        rerunAttempts = 1,
        showTestOutput = true,
        reportTitle = "Pipelines Tests",
        reportTargetDir = "build",
        cucumberOptions = @CucumberOptions(
                monochrome = true,
                features = "src/test/resources/features/",
                glue = "some.package"))
public class CucumberRunner {
}
```

And now, upon initialization, I'm getting such following  initialization errors (in this case, I'm using a minio storage server JVM client):

```java
Caused by: java.lang.NullPointerException
	at sun.text.normalizer.ICUBinary.getRequiredData(ICUBinary.java:93) ~[?:?]
	at sun.text.normalizer.NormalizerImpl.load(NormalizerImpl.java:426) ~[?:?]
	at sun.text.normalizer.Norm2AllModes$Norm2AllModesSingleton.<init>(Norm2AllModes.java:269) ~[?:?]
	at sun.text.normalizer.Norm2AllModes$NFKCSingleton.<clinit>(Norm2AllModes.java:285) ~[?:?]
	at sun.text.normalizer.Norm2AllModes.getNFKCInstance(Norm2AllModes.java:260) ~[?:?]
	at sun.text.normalizer.Normalizer2.getNFKDInstance(Normalizer2.java:121) ~[?:?]
	at sun.text.normalizer.NormalizerBase$NFKDModeImpl.<clinit>(NormalizerBase.java:179) ~[?:?]
	at sun.text.normalizer.NormalizerBase$NFKDMode.getNormalizer2(NormalizerBase.java:303) ~[?:?]
	at sun.text.normalizer.NormalizerBase.normalize(NormalizerBase.java:455) ~[?:?]
	at sun.text.normalizer.NormalizerBase.normalize(NormalizerBase.java:459) ~[?:?]
	at java.text.Normalizer.normalize(Normalizer.java:159) ~[?:?]
	at sun.security.x509.AVA.toRFC2253CanonicalString(AVA.java:987) ~[?:?]
	at sun.security.x509.RDN.toRFC2253StringInternal(RDN.java:437) ~[?:?]
	at sun.security.x509.RDN.toRFC2253String(RDN.java:417) ~[?:?]
	at sun.security.x509.X500Name.getRFC2253CanonicalName(X500Name.java:724) ~[?:?]
	at sun.security.x509.X500Name.hashCode(X500Name.java:383) ~[?:?]
	at javax.security.auth.x500.X500Principal.hashCode(X500Principal.java:488) ~[?:?]
	at java.util.HashMap.hash(HashMap.java:340) ~[?:?]
	at java.util.LinkedHashMap.get(LinkedHashMap.java:441) ~[?:?]
	at okhttp3.internal.tls.BasicTrustRootIndex.<init>(BasicTrustRootIndex.kt:59) ~[okhttp-4.3.1.jar:?]
	at okhttp3.internal.platform.Platform.buildTrustRootIndex(Platform.kt:159) ~[okhttp-4.3.1.jar:?]
	at okhttp3.internal.platform.Platform.buildCertificateChainCleaner(Platform.kt:149) ~[okhttp-4.3.1.jar:?]
	at okhttp3.internal.tls.CertificateChainCleaner$Companion.get(CertificateChainCleaner.kt:42) ~[okhttp-4.3.1.jar:?]
	at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:223) ~[okhttp-4.3.1.jar:?]
	at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:212) ~[okhttp-4.3.1.jar:?]
	at io.minio.MinioClient.<init>(MinioClient.java:672) ~[minio-6.0.13.jar:6.0.13]
	at io.minio.MinioClient.<init>(MinioClient.java:614) ~[minio-6.0.13.jar:6.0.13]
	at io.minio.MinioClient.<init>(MinioClient.java:572) ~[minio-6.0.13.jar:6.0.13]
	at io.minio.MinioClient.<init>(MinioClient.java:489) ~[minio-6.0.13.jar:6.0.13]
	at io.minio.MinioClient.<init>(MinioClient.java:420) ~[minio-6.0.13.jar:6.0.13]
```

This happens when setting `threads = 1` as well. When reverting to standard Cucumber runner, the issue vanishes.

While I'm not expecting you to debug my specific library use case,  I'm wondering if there's something else that I might have missed.

10x

**Comment by prashant-ramcharan** [comment]
Hello,

Can you try with the Courgette Spring example project? 

https://github.com/prashant-ramcharan/courgette-jvm-spring-example

**Comment by prashant-ramcharan** [comment]
Closing inactive issue.
