### ISSUE TITLE
runing paralel tests

### ISSUE THREAD

**Issue by smartserega** [prashant-ramcharan/courgette-jvm#237]
Hi, thanks for sharing information. I am trying to run tests but i have eroros log belos. If you now how to solve this please kindly let me now possible solution

java.lang.NoClassDefFoundError: org/testng/IInvokedMethodListener2
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.testng.TestNG.addServiceLoaderListeners(TestNG.java:987)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:924)
	at org.testng.TestNG.initializeEverything(TestNG.java:1018)
	at org.testng.TestNG.run(TestNG.java:1029)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: java.lang.ClassNotFoundException: org.testng.IInvokedMethodListener2
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 23 more

**Comment by prashant-ramcharan** [comment]
Hello,

This looks related to TestNG.

What version of TestNG are you using in your project?

**Comment by smartserega** [comment]
Hello, thanks for repy,

I have tried different versions (see below) but result was the same.

 testCompile group: 'org.testng', name: 'testng', version: '7.3.0'
 testCompile group: 'org.testng', name: 'testng', version: '6.14.3'
 testCompile group: 'org.testng', name: 'testng', version: '7.0.0'

**Comment by smartserega** [comment]
for start test i am using following command
-ea -Dtestng.dtd.http=true -Dcucumber.tags=@testrailID=48366

**Comment by smartserega** [comment]
my build
https://gist.github.com/smartserega/d529b95b75d6bbe1fa354f0ba058830a

runner
https://gist.github.com/smartserega/565012a3b50e0d17e0d6501f9d08db5b

thank you

**Comment by prashant-ramcharan** [comment]
Looks like you have conflicting dependencies.

Can you **remove** the following from your `build.gradle` ?

````
    testCompile group: 'org.testng', name: 'testng', version: '7.3.0'

    compile group: 'io.cucumber', name: 'cucumber-junit', version: "3.0.2"
    compile group: 'io.cucumber', name: 'cucumber-testng', version: "3.0.2"
    compile group: 'io.cucumber', name: 'cucumber-core', version: '3.0.2'
    compile group: 'io.cucumber', name: 'cucumber-java', version: '3.0.2'
````

_Courgette will include the Cucumber and TestNG dependencies for you._

**Comment by smartserega** [comment]
Thank you. removed it is really compilete without it. 
https://gist.github.com/smartserega/95745d830f7911a5d58ced0ef5cb1ffb


But problem does not changed ...  may be some thing else ? 

java.lang.NoClassDefFoundError: org/testng/IInvokedMethodListener2
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.testng.TestNG.addServiceLoaderListeners(TestNG.java:961)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:898)
	at org.testng.TestNG.initializeEverything(TestNG.java:988)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: java.lang.ClassNotFoundException: org.testng.IInvokedMethodListener2
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)

**Comment by prashant-ramcharan** [comment]
Do you get the same error using the example project here: https://github.com/prashant-ramcharan/courgette-jvm-example


I think these conflicting TestNG and older Cucumber deps may be causing the issue.

Perhaps try removing these:

````
    compile group: 'io.qameta.allure', name: 'allure-testng', version: '2.7.0'
    compile group: 'io.qameta.allure', name: 'allure-cucumber3-jvm', version: '2.7.0'
````

**Comment by smartserega** [comment]
Solved) you were right problem was in depedency ! Thanks!!

I have another problem my steps do not connect with features (same proble is in your project too https://github.com/prashant-ramcharan/courgette-jvm-example)

i lost connection between steps and features.  My be you faced with this proplem? 

Undefined step reference: User create organization uiOrganizationCreateMin apiOrganization and type attribute back less... (Ctrl+F1) 
Inspection info: Highlights steps in Cucumber (or some other Gherkin) .feature files which do not have a matching step definitions. Use a quick-fix to automatically create a new step definition.

**Comment by smartserega** [comment]
any way thank for you help. now i am trying to make paralel with docker maybe it will be esear.
have a nice day)
