### ISSUE TITLE
Running example locally via gradle task gives error

### ISSUE THREAD

**Issue by eljimso** [prashant-ramcharan/courgette-jvm#25]
getting the below error when executing the gradle tasks in the example:

```
Unexpected exception thrown.
org.gradle.internal.remote.internal.MessageIOException: Could not write '/127.0.0.1:58542'.
	at org.gradle.internal.remote.internal.inet.SocketConnection.flush(SocketConnection.java:134)
	at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionDispatch.run(MessageHub.java:325)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:51)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.writeWithNonBlockingRetry(SocketConnection.java:272)
	at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.writeBufferToChannel(SocketConnection.java:260)
	at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.flush(SocketConnection.java:254)
	at org.gradle.internal.remote.internal.inet.SocketConnection.flush(SocketConnection.java:132)
	... 7 more
```

It runs fine using the junit runner within an IDE without any issue, so the issue does seem to be in the gradle execution of this.

have you seen this issue?

**Comment by prashant-ramcharan** [comment]
1. What version of Gradle are you using?
2. Are you using the Gradle wrapper (i.e. gradlew) or the system installed Gradle?
3. What OS are you running?

**Comment by eljimso** [comment]
1. Gradle 4.1
2. Gradle Wrapper
3. Windows

**Comment by prashant-ramcharan** [comment]
This is related to this issue [GRADLE-2759](https://issues.gradle.org/browse/GRADLE-2759)

Courgette-JVM has to call System.exit() to mark the build as successful or failed. For some reason, on Windows, Gradle throws this exception. This does not happen on Ubuntu / Mac OS systems.

The Gradle error itself will not cause the build to fail.

Although this exception is displayed, your CI build tool (i.e. Jenkins / Team City) will not fail the build based on this exception.

Did you say your tests don't run with your implementation -- meaning it doesn't run any test at all?

**Comment by prashant-ramcharan** [comment]
I will remove System.exit() and throw a Courgette exception when the build fails. This should resolve this issue.

**Comment by prashant-ramcharan** [comment]
On further reflection, throwing an exception would give an unclear message when executed using Gradle or JUnit. 

The default parent runner would throw an initializationError which in this case isn't reflective of what actually happened.

Courgette-JVM uses JUnit as the entry point for running multi-threaded instances of the Cucumber CLI. The Cucumber CLI calls System.exit() to return the state of the test run. This is no different to Courgette.

Having said all that, your tests should still run fine before the Gradle exception raised. Courgette only calls System.exit(status) when all tests / threads are complete and after that point, your build will still show as "BUILD SUCCESSFUL" or "BUILD FAILED"

Please confirm whether your tests are running at all? If not, kindly share the steps to reproduce.

**Comment by prashant-ramcharan** [comment]
Closing as no further response.
