### ISSUE TITLE
Not able to upload results to reportportal when running tests in parallel 

### ISSUE THREAD

**Issue by jiteshk11** [prashant-ramcharan/courgette-jvm#254]
Full Error log: 
Exception in thread "main" Exception in thread "main" com.epam.reportportal.exception.InternalReportPortalClientException: Wait for Launch start timed out
com.epam.reportportal.exception.InternalReportPortalClientException: Wait for Launch start timed out
        at com.epam.reportportal.utils.Waiter.till(Waiter.java:126)
        at com.epam.reportportal.service.launch.SecondaryLaunch.waitForLaunchStart(SecondaryLaunch.java:56)
        at com.epam.reportportal.service.launch.SecondaryLaunch.start(SecondaryLaunch.java:88)
        at com.epam.reportportal.cucumber.AbstractReporter.beforeLaunch(AbstractReporter.java:159)
        at com.epam.reportportal.cucumber.AbstractReporter.lambda$getTestRunStartedHandler$4(AbstractReporter.java:610)
        at io.cucumber.core.eventbus.AbstractEventPublisher.send(AbstractEventPublisher.java:51)
        at io.cucumber.core.eventbus.AbstractEventBus.send(AbstractEventBus.java:12)
        at com.epam.reportportal.utils.Waiter.till(Waiter.java:126)
        at io.cucumber.core.runtime.CucumberExecutionContext.emitTestRunStarted(CucumberExecutionContext.java:64)
        at com.epam.reportportal.service.launch.SecondaryLaunch.waitForLaunchStart(SecondaryLaunch.java:56)
        at io.cucumber.core.runtime.CucumberExecutionContext.startTestRun(CucumberExecutionContext.java:52)
        at io.cucumber.core.runtime.Runtime.run(Runtime.java:77)
        at com.epam.reportportal.service.launch.SecondaryLaunch.start(SecondaryLaunch.java:88)
        at io.cucumber.core.cli.Main.run(Main.java:92)
        at io.cucumber.core.cli.Main.main(Main.java:34)
        at com.epam.reportportal.cucumber.AbstractReporter.beforeLaunch(AbstractReporter.java:159)
        at com.epam.reportportal.cucumber.AbstractReporter.lambda$getTestRunStartedHandler$4(AbstractReporter.java:610)
        at io.cucumber.core.eventbus.AbstractEventPublisher.send(AbstractEventPublisher.java:51)
        at io.cucumber.core.eventbus.AbstractEventBus.send(AbstractEventBus.java:12)
        at io.cucumber.core.runtime.CucumberExecutionContext.emitTestRunStarted(CucumberExecutionContext.java:64)
        at io.cucumber.core.runtime.CucumberExecutionContext.startTestRun(CucumberExecutionContext.java:52)
        at io.cucumber.core.runtime.Runtime.run(Runtime.java:77)
        at io.cucumber.core.cli.Main.run(Main.java:92)
        at io.cucumber.core.cli.Main.main(Main.java:34)
Exception in thread "main" com.epam.reportportal.exception.InternalReportPortalClientException: Wait for Launch start timed out
        at com.epam.reportportal.utils.Waiter.till(Waiter.java:126)
        at com.epam.reportportal.service.launch.SecondaryLaunch.waitForLaunchStart(SecondaryLaunch.java:56)
        at com.epam.reportportal.service.launch.SecondaryLaunch.start(SecondaryLaunch.java:88)
        at com.epam.reportportal.cucumber.AbstractReporter.beforeLaunch(AbstractReporter.java:159)
        at com.epam.reportportal.cucumber.AbstractReporter.lambda$getTestRunStartedHandler$4(AbstractReporter.java:610)
        at io.cucumber.core.eventbus.AbstractEventPublisher.send(AbstractEventPublisher.java:51)
        at io.cucumber.core.eventbus.AbstractEventBus.send(AbstractEventBus.java:12)
        at io.cucumber.core.runtime.CucumberExecutionContext.emitTestRunStarted(CucumberExecutionContext.java:64)
        at io.cucumber.core.runtime.CucumberExecutionContext.startTestRun(CucumberExecutionContext.java:52)
        at io.cucumber.core.runtime.Runtime.run(Runtime.java:77)
        at io.cucumber.core.cli.Main.run(Main.java:92)
        at io.cucumber.core.cli.Main.main(Main.java:34)

**Comment by prashant-ramcharan** [comment]
To upload results to reportportal using Courgette you have to use the `Courgette reportportal plugin`

https://github.com/prashant-ramcharan/courgette-jvm#report-portal-integration

I assume you using the `com.epam.reportportal` plugin? Courgette does not use this to publish to reportportal and therefore  not supported in this library.

**Comment by jiteshk11** [comment]
Thanks for reply @prashant-ramcharan , I was using the Courgette reportportal plugin. 
That issue resolved itself, not sure how. 
Appreciate you quick response.
