### ISSUE TITLE
problem with allure

### ISSUE THREAD

**Issue by smartserega** [prashant-ramcharan/courgette-jvm#257]
Hello, i have probems with starting courgette with allure (my bddrunner settings is the same with yours) my build file is following https://gist.github.com/smartserega/4ec21a5769915de0b90f35f159e91a2b 

please kindly let me know possible solution. Thank you in advance.

```
java.lang.IllegalArgumentException: The plugin specification 'io.qameta.allure.cucumber6jvm.AllureCucumber6Jvm' has a problem:

Could not load plugin class 'io.qameta.allure.cucumber6jvm.AllureCucumber6Jvm'.

Plugin specifications should have the format of PLUGIN[:[PATH|[URI [OPTIONS]]]

Valid values for PLUGIN are: default_summary, html, json, junit, message, null_summary, pretty, progress, rerun, summary, teamcity, testng, timeline, unused, usage

PLUGIN can also be a fully qualified class name, allowing registration of 3rd party plugins. The 3rd party plugin must implement io.cucumber.plugin.Plugin

	at io.cucumber.core.options.PluginOption.createCouldNotLoadClass(PluginOption.java:168)
	at io.cucumber.core.options.PluginOption.parsePluginName(PluginOption.java:146)
	at io.cucumber.core.options.PluginOption.parse(PluginOption.java:101)
	at io.cucumber.core.options.RuntimeOptionsBuilder.addPluginName(RuntimeOptionsBuilder.java:68)
	at io.cucumber.core.options.CommandlineOptionsParser.parse(CommandlineOptionsParser.java:127)

```

**Comment by prashant-ramcharan** [comment]
Please refer to the example project: https://github.com/prashant-ramcharan/courgette-jvm-allure-example
