### ISSUE TITLE
problem with java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by yariks80** [prashant-ramcharan/courgette-jvm#303]
version - 'io.github.prashant-ramcharan:courgette-jvm:5.9.2'

java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at java.lang.ProcessEnvironment.addToEnv(ProcessEnvironment.java:344)
	at java.lang.ProcessEnvironment.toEnvironmentBlock(ProcessEnvironment.java:321)
	at java.lang.ProcessEnvironment.toEnvironmentBlock(ProcessEnvironment.java:349)
	at java.lang.ProcessImpl.start(ProcessImpl.java:94)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	at courgette.runtime.CourgetteFeatureRunner.run(CourgetteFeatureRunner.java:28)
	at courgette.runtime.CourgetteRunner.runFeature(CourgetteRunner.java:245)
	at courgette.runtime.CourgetteRunner.lambda$run$3(CourgetteRunner.java:75)
	at courgette.runtime.CourgetteRunner$$Lambda$99/581661871.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space: failed reallocation of scalar replaced objects

**Comment by prashant-ramcharan** [comment]
1. Are you passing any `-Xms` and `Xmx` memory args to the `gradle` or `maven` process?
2. How much memory does your machine have?
3. How many tests are you running in parallel?
4. What version of Java are you using?
5. Does this happen on every run?
6. What Courgette run level are you using?

**Comment by yariks80** [comment]
1) GRADLE_OPTS= -Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 in Gradle 
2)64 
3) 240 test cases
4) Java 1.8
5) yes it  is happen every run
6) runLevel = CourgetteRunLevel.SCENARIO,

**Comment by prashant-ramcharan** [comment]
A max heap size of `2GB` is quiet low considering you running 240 scenarios.

How many Courgette threads you using?

Can you try setting the `jvmargs` for the gradle daemon process by adding this to your `gradle.properties` ?

````gradle
org.gradle.jvmargs=-Xmx16g
````

**Comment by yariks80** [comment]
We have between  5-10 threads in Jenkins job.  What kind  of settings we need setup in job better

**Comment by prashant-ramcharan** [comment]
1. Increase the `-Xmx` memory in `org.gradle.jvmargs` or `GRADLE_OPTS` [read more here](http://sorcersoft.org/project/site/gradle/userguide/build_environment.html#sec:gradle_configuration_properties)
2. Add a this to your `build.gradle` (_you should tweak the memory for your test needs / environment etc_)

````gradle
tasks.withType(Test) {
    jvmArgs = ['-Xmx8g']
}
````
