### ISSUE TITLE
courgette.runtime.CourgetteTestErrorException while running the test in parallel

### ISSUE THREAD

**Issue by MadhuQAAutomation** [prashant-ramcharan/courgette-jvm#331]
Hi - I am using the Courgette-JVM library for running the test in parallel. When I execute the test from Test Runner, got the below exception:
courgette.runtime.CourgetteTestErrorException: There were errors when running the test. Refer to the console for more information.

Process finished with exit code -2

When I try to run the same test from command line using mvn verify command, getting the below error :

java.io.IOException: Cannot run program "java": CreateProcess error=206, The filename or extension is too long
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at courgette.runtime.CourgetteFeatureRunner.run(CourgetteFeatureRunner.java:32)
        at courgette.runtime.CourgetteRunner.runFeature(CourgetteRunner.java:236)
        at courgette.runtime.CourgetteRunner.lambda$run$3(CourgetteRunner.java:85)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: CreateProcess error=206, The filename or extension is too long
        at java.base/java.lang.ProcessImpl.create(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:487)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)

Courgette Version : 6.4.2

**Comment by MadhuQAAutomation** [comment]
![image](https://user-images.githubusercontent.com/93340435/168577318-b3680f23-5104-4414-8348-2208092cd503.png)

**Comment by MadhuQAAutomation** [comment]
Hi - I did the workaround as mentioned in the example. However, still its throwing the below exception: 

![image](https://user-images.githubusercontent.com/93340435/169589088-26b191d7-a490-46e9-87cf-4e216f754469.png)


![image](https://user-images.githubusercontent.com/93340435/169589007-4fb29910-d3ca-44e1-8a8d-7ff9ced73d59.png)


Also, I have mentioned the correct glue path in the runner file. However step not defined message is displayed as well.

Undefined scenarios:
1 Scenarios (1 undefined)
16 Steps (15 skipped, 1 undefined)

![image](https://user-images.githubusercontent.com/93340435/169589489-e9d5947f-1d59-4e32-80ae-36be6247ecdc.png)

**Comment by prashant-ramcharan** [comment]
Hi , 

1. Did you manage to run the [example projec](https://github.com/prashant-ramcharan/courgette-jvm-classpath-example)t without any issues?

2. Can you see the step def class in: `target/test-classes/com/automation/steps` ?

3. Do you have a project to replicate this? It's difficult to debug without seeing the project setup, pom structure etc..

**Comment by MadhuQAAutomation** [comment]
Hi Prashant - Hi Prashant -I was able to run the test project with out any
issue.
I am also able to see the step def folder in target/test-classes/....
Folder too

Coming to project related, since it's official and company confidential, I
might not be able to share.

Is it possible to setup call to go through this?

Thank you
Madhu

**Comment by prashant-ramcharan** [comment]
Can you please provide the output for the following:

 `mvn test -X` 

`mvn dependency:tree`

**Comment by MadhuQAAutomation** [comment]
Hi - Prashant - I have sent an email for the same.

**Comment by prashant-ramcharan** [comment]
Update: Issue was related to the `Cucumber Glue` in the Courgette runner.
