### ISSUE TITLE
mvn verify throws There was an error in the forked process at the end of the test execution using Courgette

### ISSUE THREAD

**Issue by MadhuQAAutomation** [prashant-ramcharan/courgette-jvm#335]
Hi Prashant - While executing the Cucumber tests using Courgette by enabling the parallel (thread count >1), the below error is thrown when the tests has some failures.

There was an error in the forked process
org.apache.maven.surefire.testset.TestSetFailedException: java.lang.NullPointerException
	at org.apache.maven.surefire.common.junit4.JUnit4RunListener.rethrowAnyTestMechanismFailures(JUnit4RunListener.java:209)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:138)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.lang.NullPointerException
	at org.apache.maven.surefire.junitcore.NonConcurrentRunListener.describesNewTestSet(NonConcurrentRunListener.java:93)
	at org.apache.maven.surefire.junitcore.NonConcurrentRunListener.finishLastTestSetIfNecessary(NonConcurrentRunListener.java:77)
	at org.apache.maven.surefire.junitcore.NonConcurrentRunListener.testFailure(NonConcurrentRunListener.java:130)
	at org.junit.runner.notification.SynchronizedRunListener.testFailure(SynchronizedRunListener.java:94)
	at org.junit.runner.notification.RunNotifier$6.notifyListener(RunNotifier.java:177)
	at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
	at org.junit.runner.notification.RunNotifier.fireTestFailures(RunNotifier.java:173)
	at org.junit.runner.notification.RunNotifier.fireTestFailure(RunNotifier.java:167)
	at org.apache.maven.surefire.common.junit4.Notifier.fireTestFailure(Notifier.java:114)
	at courgette.runtime.junit.CourgetteJUnitRunner.lambda$notifyTestFailure$1(CourgetteJUnitRunner.java:87)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at courgette.runtime.junit.CourgetteJUnitRunner.notifyTestFailure(CourgetteJUnitRunner.java:84)
	at courgette.api.junit.Courgette.run(Courgette.java:86)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
	... 7 more

Surefire Plugin config:
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.19.1</version>
                <configuration>
                    <useSystemClassLoader>false</useSystemClassLoader>
                    <failIfNoSpecifiedTests>true</failIfNoSpecifiedTests>
                    <includes>
                        <includes>**/runner/CourgetteTestRunner.class</includes>
                    </includes>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.apache.maven.surefire</groupId>
                        <artifactId>surefire-junit47</artifactId>
                        <version>2.19.1</version>
                    </dependency>
                </dependencies>

**Comment by MadhuQAAutomation** [comment]
Hi Prashant - Please find the below details :


Surefire Plugin Config :

<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>2.17</version>
    <configuration>
        <useSystemClassLoader>false</useSystemClassLoader>
        <failIfNoSpecifiedTests>true</failIfNoSpecifiedTests>
        <includes>
            <includes>**/runner/CourgetteTestRunner.class</includes>
        </includes>
    </configuration>
    <dependencies>
      <dependency>
            <groupId>org.apache.maven.surefire</groupId>
            <artifactId>surefire-junit47</artifactId>
            <version>2.17</version>
        </dependency>
    </dependencies>
</plugin>


Courgette Version :

<dependency>
    <groupId>io.github.prashant-ramcharan</groupId>
    <artifactId>courgette-jvm</artifactId>
    <version>6.5.0</version>
</dependency>

Maven Version: 3.8.4


   - When your feature file passes, then you wont get this. On the
   other hand, if the test fails, then this error will occur. This is
   repeatable  , when your test has failures.



   - I have upgraded to 3.X.X.X . It didnt work and hence came to 2.19.1.



   - Today, I commented the junit dependency in Maven sure fire plugin.
   This time it worked  and the test reports (Courgette and master thought
   reports) got generated with failed feature files. Not sure if there is any
   issue with junit.

**Comment by prashant-ramcharan** [comment]
> Today, I commented the junit dependency in Maven sure fire plugin.
   This time it worked  and the test reports (Courgette and master thought
   reports) got generated with failed feature files. Not sure if there is any
   issue with junit.

Most likely as I'm unable to reproduce this.
