### ISSUE TITLE
Enable to Execute Test Runner

### ISSUE THREAD

**Issue by viswanathd0510** [prashant-ramcharan/courgette-jvm#379]
Hi i am getting the below error while try to execute test runner class in eclipse

java.lang.IllegalArgumentException: Invalid tag expression at 'TestRunner.Test_Runner'
	at io.cucumber.core.options.CucumberOptionsAnnotationParser.addTags(CucumberOptionsAnnotationParser.java:79)
	at io.cucumber.core.options.CucumberOptionsAnnotationParser.parse(CucumberOptionsAnnotationParser.java:40)
	at io.cucumber.junit.Cucumber.<init>(Cucumber.java:122)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:90)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:76)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:49)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:513)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: io.cucumber.tagexpressions.TagExpressionException: Tag expression '@UrlLaunch, @HotelSearch, @SelectHotel, @BookHotel, @ConfirmBoking' could not be parsed because of syntax error: expected operator
	at io.cucumber.tagexpressions.TagExpressionParser.check(TagExpressionParser.java:136)
	at io.cucumber.tagexpressions.TagExpressionParser.parse(TagExpressionParser.java:74)
	at io.cucumber.tagexpressions.TagExpressionParser.parse(TagExpressionParser.java:27)
	at io.cucumber.core.options.CucumberOptionsAnnotationParser.addTags(CucumberOptionsAnnotationParser.java:77)
	... 18 more
![Screenshot (42)](https://github.com/prashant-ramcharan/courgette-jvm/assets/105190208/aabb1035-59c3-4783-a514-b8dba288c9c3)

**Comment by prashant-ramcharan** [comment]
Hi, you are using a **Cucumber runner** as per your screenshot and not a Courgette runner.

Please refer to the [Cucumber documentation](https://cucumber.io/docs/cucumber/api/) on the correct usage of tag expressions.
