### ISSUE TITLE
Not able to run Courgette class

### ISSUE THREAD

**Issue by sobi-ki** [prashant-ramcharan/courgette-jvm#384]
Hi,

I was able to run via the command line yesterday successfully. 
Overnight some dependencies were updated, and all tests failed.
Not sure if dependencies are used within Courgette.

Any advice on this pls? Thx 

`Starting Gradle Daemon...
Gradle Daemon started in 3 s 343 ms

> Task :compileJava UP-TO-DATE
> Task :pluginDescriptors UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :compileTestJava UP-TO-DATE
> Task :pluginUnderTestMetadata UP-TO-DATE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :test
Exception in thread "main" Exception in thread "main" io.cucumber.core.exception.CucumberException: java.util.ServiceConfigurationError: sun.util.locale.provider.LocaleDataMetaInfo: Unable to load sun.util.resources.cldr.provider.CLDRLocaleDataMetaInfo
	at io.cucumber.core.plugin.PluginFactory.newInstance(PluginFactory.java:120)
	at io.cucumber.core.plugin.PluginFactory.instantiate(PluginFactory.java:99)
	at io.cucumber.core.plugin.PluginFactory.create(PluginFactory.java:63)
	at io.cucumber.core.plugin.Plugins.createPlugins(Plugins.java:32)
	at io.cucumber.core.plugin.Plugins.<init>(Plugins.java:25)
	at io.cucumber.core.runtime.Runtime$Builder.build(Runtime.java:168)
	at io.cucumber.core.cli.Main.run(Main.java:85)
	at io.cucumber.core.cli.Main.main(Main.java:30)
io.cucumber.core.exception.CucumberException: java.util.ServiceConfigurationError: sun.util.locale.provider.LocaleDataMetaInfo: Unable to load sun.util.resources.cldr.provider.CLDRLocaleDataMetaInfo
Caused by: java.util.ServiceConfigurationError: sun.util.locale.provider.LocaleDataMetaInfo: Unable to load sun.util.resources.cldr.provider.CLDRLocaleDataMetaInfo
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:582)
	at java.base/java.util.ServiceLoader.loadProvider(ServiceLoader.java:854)
	at java.base/java.util.ServiceLoader$ModuleServicesLookupIterator.hasNext(ServiceLoader.java:1077)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
	at java.base/sun.util.cldr.CLDRLocaleProviderAdapter$1.run(CLDRLocaleProviderAdapter.java:89)
	at java.base/sun.util.cldr.CLDRLocaleProviderAdapter$1.run(CLDRLocaleProviderAdapter.java:86)
	at java.base/java.security.AccessController.doPrivileged(Native Method)	at io.cucumber.core.plugin.PluginFactory.newInstance(PluginFactory.java:120)
	at java.base/sun.util.cldr.CLDRLocaleProviderAdapter.<init>(CLDRLocaleProviderAdapter.java:86)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)	at io.cucumber.core.plugin.PluginFactory.instantiate(PluginFactory.java:99)
	at io.cucumber.core.plugin.PluginFactory.create(PluginFactory.java:63)
	at io.cucumber.core.plugin.Plugins.createPlugins(Plugins.java:32)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at io.cucumber.core.plugin.Plugins.<init>(Plugins.java:25)	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at java.base/sun.util.locale.provider.LocaleProviderAdapter.forType(LocaleProviderAdapter.java:176)	at io.cucumber.core.runtime.Runtime$Builder.build(Runtime.java:168)
	at io.cucumber.core.cli.Main.run(Main.java:85)	at java.base/sun.util.locale.provider.LocaleProviderAdapter.findAdapter(LocaleProviderAdapter.java:279)
	at java.base/sun.util.locale.provider.LocaleProviderAdapter.getAdapter(LocaleProviderAdapter.java:250)
	at io.cucumber.core.cli.Main.main(Main.java:30)	at java.base/java.util.Calendar.createCalendar(Calendar.java:1692)
	at java.base/java.util.Calendar.getInstance(Calendar.java:1660)
	at java.base/java.text.SimpleDateFormat.initializeCalendar(SimpleDateFormat.java:676)
	at java.base/java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:620)
	at io.cucumber.core.internal.com.fasterxml.jackson.databind.util.StdDateFormat.<clinit>(StdDateFormat.java:116)
	at io.cucumber.core.internal.com.fasterxml.jackson.databind.ObjectMapper.<clinit>(ObjectMapper.java:384)
	at io.cucumber.core.plugin.Jackson.<clinit>(Jackson.java:13)
	at io.cucumber.core.plugin.HtmlFormatter.<init>(HtmlFormatter.java:17)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at io.cucumber.core.plugin.PluginFactory.newInstance(PluginFactory.java:116)
	... 7 more

Caused by: java.lang.UnsupportedClassVersionError: sun/util/resources/cldr/provider/CLDRLocaleDataMetaInfo has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

`

**Comment by sobi-ki** [comment]
This seems to be related to spring
