### ISSUE TITLE
error=206, The filename or extension is too long  trying to execute my project with courgette-jvm

### ISSUE THREAD

**Issue by xyuste** [prashant-ramcharan/courgette-jvm#405]
Hi
I am trying to execute with courgette-jvm my project and I have the following error:

java.io.IOException: Cannot run program "java": CreateProcess error=206, The filename or extension is too long
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at courgette.runtime.CourgetteFeatureRunner.run(CourgetteFeatureRunner.java:33)
        at courgette.runtime.CourgetteRunner.runFeature(CourgetteRunner.java:231)
        at courgette.runtime.CourgetteRunner.lambda$run$3(CourgetteRunner.java:82)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: CreateProcess error=206, The filename or extension is too long
        at java.base/java.lang.ProcessImpl.create(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:487)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 8 more
java.io.IOException: Cannot run program "java": CreateProcess error=206, The filename or extension is too long
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at courgette.runtime.CourgetteFeatureRunner.run(CourgetteFeatureRunner.java:33)
        at courgette.runtime.CourgetteRunner.runFeature(CourgetteRunner.java:231)
        at courgette.runtime.CourgetteRunner.rerunFeature(CourgetteRunner.java:246)
        at courgette.runtime.CourgetteRunner.lambda$run$3(CourgetteRunner.java:99)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: CreateProcess error=206, The filename or extension is too long
        at java.base/java.lang.ProcessImpl.create(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:487)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 9 more
[Courgette Runner] There was an unexpected error processing the individual Cucumber report files and Courgette was unable to create any reports for this test run.  

What do you think about this error? what is the problem??
Many thanks

**Comment by xyuste** [comment]
Hi,
I have found the previous issue:
https://github.com/prashant-ramcharan/courgette-jvm/issues/250
I will try to follow the indicate solution
Regards
