### ISSUE TITLE
Not able to run from jenkins 

### ISSUE THREAD

**Issue by Newvamshi** [prashant-ramcharan/courgette-jvm#412]
java.io.IOException: Cannot run program "java": CreateProcess error=206, The filename or extension is too long
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at courgette.runtime.CourgetteFeatureRunner.run(CourgetteFeatureRunner.java:44)
	at courgette.runtime.CourgetteRunner.runFeature(CourgetteRunner.java:247)
	at courgette.runtime.CourgetteRunner.lambda$run$3(CourgetteRunner.java:85)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: CreateProcess error=206, The filename or extension is too long
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:487)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 8 more
[Courgette Runner] There was an unexpected error processing the individual Cucumber report files and Courgette was unable to create any reports for this test run.
??????????????????????????????????????????????????
             Courgette Test Statistics          
???????????????????????????????????????????????????
Summary:	0% passed, 100% failed
Duration:	0 min, 1 sec
Run Level:	Feature
Total:		51
Passed:		0
Failed:		51
???????????????????????????????????????????????????

[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.806 s - in testRunner.TestRunner
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14.589 s
[INFO] Finished at: 2024-07-30T21:19:11-07:00
[INFO] ------------------------------------------------------------------------

getting above error while running from jenkins .Build is success but tests are not running.

**Comment by prashant-ramcharan** [comment]
https://github.com/prashant-ramcharan/courgette-jvm-classpath-example

**Comment by Newvamshi** [comment]
tried this tests are not getting started.
<img width="430" alt="Screenshot 2024-08-01 001719" src="https://github.com/user-attachments/assets/78b17acb-1dff-4006-93ce-7dcfde22f056">

**Comment by Newvamshi** [comment]
with jenkins

**Comment by prashant-ramcharan** [comment]
* Does the tests run fine locally?
* How are you running the tests in Jenkins (maven, docker / other)?
* Are you able to provide a demo project including the Jenkins pipeline file so that I can reproduce it?

**Comment by prashant-ramcharan** [comment]
Closing inactive issue
