### ISSUE TITLE
HTML reports not created

### ISSUE THREAD

**Issue by MadhuQAAutomation** [prashant-ramcharan/courgette-jvm#423]
Hi @prashant-ramcharan - Today I  upgraded to courgette 6.18.0 from 6.13.0. When I ran my test suite which contains ~ 300+ feature files. I got the below error in the console:

`[ERROR] Tests run: 331, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1825 s <<< FAILURE! -- in runners.RunCucumberIT
[ERROR] runners.RunCucumberIT -- Time elapsed: 1825 s <<< ERROR!
com.google.gson.JsonSyntaxException: 
com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 3727266 path $[320].elements[1].steps[6].match.
See https://github.com/google/gson/blob/main/Troubleshooting.md#malformed-json
	at com.google.gson.internal.Streams.parse(Streams.java:58)
	at com.google.gson.JsonParser.parseReader(JsonParser.java:146)
	at com.google.gson.JsonParser.parseReader(JsonParser.java:110)
	at com.google.gson.JsonParser.parse(JsonParser.java:171)
	at courgette.runtime.report.JsonReportParser.parseJsonReport(JsonReportParser.java:107)
	at courgette.runtime.report.JsonReportParser.createFeatures(JsonReportParser.java:69)
	at courgette.runtime.report.JsonReportParser.createFeatures(JsonReportParser.java:60)
	at courgette.runtime.CourgetteRunner.createCucumberReport(CourgetteRunner.java:127)
	at courgette.api.junit.Courgette.run(Courgette.java:60)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 3727266 path $[320].elements[1].steps[6].match.
See https://github.com/google/gson/blob/main/Troubleshooting.md#malformed-json
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1754)
	at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1120)
	at com.google.gson.stream.JsonReader.nextName(JsonReader.java:881)
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:879)
	at com.google.gson.internal.bind.TypeAdapters$28.read(TypeAdapters.java:820)
	at com.google.gson.internal.Streams.parse(Streams.java:46)
	... 8 more`
	
	Test Runner:
![image](https://github.com/user-attachments/assets/61318de8-0898-4ba7-b498-1d39e27e7f0e)

	
 generateCourgetteRunLog is set to true. But in the target folder, I don't see any courgette folder that got created and no log file as well. 

![image](https://github.com/user-attachments/assets/8479c736-6e29-4011-8b71-188422d5442c)

Till last week, I was using courgette version 6.13.0 and it was running fine without any issue. 

Java version : Java 21
OS : Mac Sequoia 
Courgette version : 6.18.0
cucumber version: 7.20.1

**Comment by prashant-ramcharan** [comment]
Hi, does this happen on every run or is it intermittent?

Could it be related this issue?

https://github.com/prashant-ramcharan/courgette-jvm/issues/422#issuecomment-2498542117

**Comment by MadhuQAAutomation** [comment]
Hi - This is occurring on every run. I tried for 5 times and all those 5 runs, I saw the same behavior. Becuase of this, I reverted back to 6.13.0.

**Comment by MadhuQAAutomation** [comment]
Hi @prashant-ramcharan - As mentioned in #422, in my test suite also, few of the feature file names were having spaces. After fixing those feature files by replacing the spaces with "_", I didn't got the errors as before and the HTML report also created successfully.

**Comment by prashant-ramcharan** [comment]
Thanks for confirming. 

I should be able to remove any whitespaces from the feature file names before the test run. Will add this to the next release.

**Comment by MadhuQAAutomation** [comment]
Sounds good, thanks!

**Comment by MadhuQAAutomation** [comment]
> Thanks for confirming.
> 
> What was your feature file name before removing the spaces?

Eg: TC01_Verify_email id is_valid_and check for error_message

**Comment by prashant-ramcharan** [comment]
I will provide a fix for this. Thanks!

**Comment by prashant-ramcharan** [comment]
This is now fixed in Courgette version `6.18.1`

**Comment by MadhuQAAutomation** [comment]
Thanks @prashant-ramcharan.
