### ISSUE TITLE
Issue while trying to run courgette-jvm example

### ISSUE THREAD

**Issue by fellajim** [prashant-ramcharan/courgette-jvm#5]
I'm having this issue while I tried to run the Courgette-JVM Example or my tests runners 

Exception in thread "main" cucumber.runtime.CucumberException: java.io.FileNotFoundException: /tmp7ccaa3ac150143b1af0477dd4cb036b5_thread_report_profile-tests-1670854404.json (Permission non accordée)
	at cucumber.runtime.formatter.PluginFactory.create(PluginFactory.java:89)
	at cucumber.runtime.RuntimeOptions.getPlugins(RuntimeOptions.java:245)
	at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:291)
	at com.sun.proxy.$Proxy0.uri(Unknown Source)
	at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:160)
	at cucumber.runtime.Runtime.run(Runtime.java:122)
	at cucumber.api.cli.Main.run(Main.java:36)
	at cucumber.api.cli.Main.main(Main.java:18)
Caused by: java.io.FileNotFoundException: /tmp7ccaa3ac150143b1af0477dd4cb036b5_thread_report_profile-tests-1670854404.json (Permission non accordée)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at cucumber.runtime.io.URLOutputStream.<init>(URLOutputStream.java:34)
	at cucumber.runtime.io.URLOutputStream.<init>(URLOutputStream.java:24)
	at cucumber.runtime.formatter.PluginFactory.convertOrNull(PluginFactory.java:142)
	at cucumber.runtime.formatter.PluginFactory.instantiate(PluginFactory.java:99)
	at cucumber.runtime.formatter.PluginFactory.create(PluginFactory.java:87)

**Comment by prashant-ramcharan** [comment]
Do you have permission to the /tmp folder in your file system?

If not, try using this from the terminal --> chmod 1777 /tmp

Failing that, I think I may know the issue here.

Let me know if you still experience issues after trying the above.

**Comment by fellajim** [comment]
I still have the same issue and I'm using Ubuntu 16.04 LTS.

**Comment by prashant-ramcharan** [comment]
Ok thanks for confirming -- will fix.

**Comment by prashant-ramcharan** [comment]
This is fixed in version 1.3.2

@fellajim try it out and let me know.

**Comment by fellajim** [comment]
The bug is fixed however I can't run tests because the courgette runner doesn't find steps definition so it exits with the message: 
You can implement missing steps with the snippets below:

When("^Login with admin account$", () -> {
......

**Comment by PrashantRiverIsland** [comment]
This is not an issue with Courgette-JVM. This is an issue with your test set-up.

Make sure your **glue** is pointing to the correct package.

Look at the example here [https://github.com/prashant-ramcharan/courgette-jvm-example/blob/master/src/test/java/ScenarioSuite.java](url)

**Comment by prashant-ramcharan** [comment]
This is not an issue with Courgette-JVM. This is an issue with your test set-up.

Make sure your **glue** is pointing to the correct package.

Look at the example here [https://github.com/prashant-ramcharan/courgette-jvm-example/blob/master/src/test/java/ScenarioSuite.java](url)

**Comment by fellajim** [comment]
@RunWith(Courgette.class)
@CourgetteOptions(
        threads = 10,
        runLevel = CourgetteRunLevel.SCENARIO,
        rerunFailedScenarios = true,
        showTestOutput = true,
        cucumberOptions = @CucumberOptions(
                features = "src/test/resources/login",
                glue = "src/test/java/login",
                tags = {"@PrestaNonRefDay"},
                plugin = {
                        "pretty",
                        "json:target/courgette-report/courgette.json",
                        "html:target/courgette-report/courgette.html"}
        ))


2017-07-21 10:04 GMT+02:00 Prashant Ramcharan <notifications@github.com>:

**Comment by prashant-ramcharan** [comment]
Cucumber expects the **glue** to be a **package name** and not a file path.

So change this line 
glue = "src/test/java/login"

to this line
**glue = "login"**

_Note. You step definitions must be the package name "login"_

**Comment by fellajim** [comment]
Okay thank you very much and I am sorry :)

Have a good day

2017-07-21 10:37 GMT+02:00 Prashant Ramcharan <notifications@github.com>:
