### ISSUE TITLE
initializationError

### ISSUE THREAD

**Issue by niagara1983** [prashant-ramcharan/courgette-jvm#55]
Hi prashant,
I just upgraded to version 2.3.2 and my scenario are passing but at the end of the run 
I get the following error
`java.lang.StringIndexOutOfBoundsException: start 0, end -1, length 0
	at java.base/java.lang.AbstractStringBuilder.checkRangeSIOOBE(AbstractStringBuilder.java:1698)
	at java.base/java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:991)
	at java.base/java.lang.StringBuilder.substring(StringBuilder.java:77)
	at courgette.runtime.report.JsonReportParser.addStepRowData(JsonReportParser.java:218)
	at courgette.runtime.report.JsonReportParser.lambda$addSteps$2(JsonReportParser.java:163)
	at java.base/java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:927)
	at courgette.runtime.report.JsonReportParser.addSteps(JsonReportParser.java:144)
	at courgette.runtime.report.JsonReportParser.lambda$parseJsonReport$1(JsonReportParser.java:135)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
	at courgette.runtime.report.JsonReportParser.parseJsonReport(JsonReportParser.java:135)
	at courgette.runtime.report.JsonReportParser.getReportFeatures(JsonReportParser.java:49)
	at courgette.runtime.CourgetteHtmlReporter.generateHtmlReport(CourgetteHtmlReporter.java:59)
	at courgette.runtime.CourgetteHtmlReporter.create(CourgetteHtmlReporter.java:51)
	at courgette.runtime.CourgetteRunner.createCourgetteReport(CourgetteRunner.java:129)
	at courgette.api.junit.Courgette.run(Courgette.java:89)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:116)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:59)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:39)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy1.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.base/java.lang.Thread.run(Thread.java:844)`

it looks this occurs during the generation of the report. Any idea how to fix this?

**Comment by prashant-ramcharan** [comment]
Hi @niagara1983 

I can't reproduce this issue on my side but it looks like a problem parsing your row data.

I assume you using Cucumber data tables in your scenarios?

Can you please provide the cucumber json that gets generated after your test run?

**Comment by niagara1983** [comment]
your assumption is correct. But I don't have a commented out line in the scenarios. see attached file for the cucumber.json 
[cucumber.json.zip](https://github.com/prashant-ramcharan/courgette-jvm/files/2041115/cucumber.json.zip)

**Comment by prashant-ramcharan** [comment]
Unfortunately, I cannot open the zip file, says its corrupted.

**Comment by prashant-ramcharan** [comment]
Thanks - this works.

So the issue is in the Courgette json parser which assumed your Cucumber data table contained a **row header + row cell**.

Similar to these examples: https://github.com/cucumber/cucumber/wiki/Scenario-Outlines

In your case, your tests only has a row cell therefore the Courgette json parser threw an exception.

**Comment by niagara1983** [comment]
that makes totally sense because this issue does not occur in other scenarios. Thanks Prashant. Any idea on when you are planning the next release?

**Comment by prashant-ramcharan** [comment]
In addition to this fix, I will be upgrading to Cucumber-JVM 3.0.1 in the next release which should be in a day or 2.

**Comment by prashant-ramcharan** [comment]
This is now released.

**Comment by niagara1983** [comment]
Thanks a lot prashant!

**Comment by prashant-ramcharan** [comment]
Can you run any feature successfully using Cucumber version 3.0.1?

Without using the Courgette runner.

**Comment by prashant-ramcharan** [comment]
Add this to your build.gradle

````gradle
compile group: 'io.cucumber', name: 'cucumber-groovy', version: '2.0.1'
````

**Comment by niagara1983** [comment]
I already had that line in my build.gradle file. could it be a conflict between cucumber core 2.0.1 and the one that comes with courgette-jvm:2.4.0, which is 3.0.1. 

`import org.apache.tools.ant.taskdefs.condition.Os


buildscript {
	repositories {
		jcenter()
		mavenCentral()
	}
	dependencies {

		classpath "org.gebish:geb-core:2.1"

		classpath "org.gebish:geb-gradle:2.1"
	}
}

ext {
	ext {
		groovyVersion = '2.4.15'
		gebVersion = '2.1'
		seleniumVersion = '3.12.0'
		chromeDriverVersion = '2.36'
		geckoDriverVersion = 'v0.20.1'
		ieDriverVersion = '3.5'
	}
}

apply plugin: "groovy"
apply plugin: 'java'
apply from: "gradle/osSpecificDownloads.gradle"
apply from: "gradle/idea/idea.gradle"
apply plugin: 'idea'


repositories {
	mavenCentral()
	jcenter()
}

dependencies {

	// geb
	testCompile ("org.gebish:geb-core:$gebVersion") {
		exclude group: 'com.google.guava'
	}

	// groovy
	testCompile "org.codehaus.groovy:groovy-all:$groovyVersion"

	// Drivers
	testCompile "org.seleniumhq.selenium:selenium-chrome-driver:$seleniumVersion"
	testCompile "org.seleniumhq.selenium:selenium-firefox-driver:$seleniumVersion"
	testCompile ("org.seleniumhq.selenium:selenium-ie-driver:$seleniumVersion") {
		exclude group: 'com.google.guava'
	}
	testCompile "org.seleniumhq.selenium:selenium-safari-driver:$seleniumVersion"
	testCompile 'commons-io:commons-io:2.4'

	// Selenium support
	testCompile "org.seleniumhq.selenium:selenium-support:$seleniumVersion"
	testCompile "org.seleniumhq.selenium:selenium-api:$seleniumVersion"


	compile group: 'io.cucumber', name: 'cucumber-groovy', version: '2.0.1'


	//courgette
    testCompile 'io.github.prashant-ramcharan:courgette-jvm:2.4.0'

	// https://mvnrepository.com/artifact/org.apache.poi/poi
	compile group: 'org.apache.poi', name: 'poi', version: '3.17'
	// https://mvnrepository.com/artifact/org.apache.xmlbeans/xmlbeans
	compile group: 'org.apache.xmlbeans', name: 'xmlbeans', version: '2.6.0'

	// https://mvnrepository.com/artifact/org.apache.poi/poi-ooxml
	compile group: 'org.apache.poi', name: 'poi-ooxml', version: '3.17'
	// https://mvnrepository.com/artifact/org.apache.poi/poi-ooxml-schemas
	compile group: 'org.apache.poi', name: 'poi-ooxml-schemas', version: '3.17'

	// https://mvnrepository.com/artifact/org.apache.poi/ooxml-schemas
	compile group: 'org.apache.poi', name: 'ooxml-schemas', version: '1.3'





}



task runFeatures(type: Test) {
	include '**/suites/FeatureSuite.class'
	outputs.upToDateWhen { false }
}

task runScenarios(type: Test) {
	include '**/suites/ScenarioSuite.class'
	outputs.upToDateWhen { false }
}`

**Comment by prashant-ramcharan** [comment]
try changing to **testCompile**

````gradle
testCompile group: 'io.cucumber', name: 'cucumber-groovy', version: '2.0.1'
````

**Comment by prashant-ramcharan** [comment]
cucumber-groovy simply inherits the current cucumber-core module so there wont be any conflicts.

**Comment by prashant-ramcharan** [comment]
Right, so the cucumber-groovy library is not updated to run with Cucumber 3.

The GroovyBackend is missing the following constructor so Cucumber 3 cannot create the runtime.

````java
public GroovyBackend(ResourceLoader resourceLoader, TypeRegistry typeRegistry) {
}
````

https://github.com/cucumber/cucumber-jvm-groovy/blob/master/groovy/src/main/java/cucumber/runtime/groovy/GroovyBackend.java#L57-L59

___
Until cucumber-groovy is updated to support cucumber 3, I do have a workaround for you.

In your build.gradle, add this.

````gradle
    //courgette
    testCompile ('io.github.prashant-ramcharan:courgette-jvm:2.4.0') {
        exclude group: 'io.cucumber'
    }

    testCompile 'io.cucumber:cucumber-core:2.4.0'
    testCompile 'io.cucumber:cucumber-java:2.4.0'
    testCompile 'io.cucumber:cucumber-junit:2.4.0'

    testCompile group: 'io.cucumber', name: 'cucumber-groovy', version: '2.0.1'
````

I can confirm this works!
