### ISSUE TITLE
Getting 'java.lang.IncompatibleClassChangeError: Implementing class' while trying to run test with 

### ISSUE THREAD

**Issue by JuLoral** [prashant-ramcharan/courgette-jvm#72]
Hi!
I'm using Gradle+Cucumber-JVM.
Have added courgette-jvm as dependency to my biuld.gradle.
Created runner class as shown in the example:
```
import courgette.api.CourgetteOptions;
import courgette.api.CourgetteRunLevel;
import courgette.api.junit.Courgette;
import cucumber.api.CucumberOptions;
import org.junit.runner.RunWith;

@RunWith(Courgette.class)
@CourgetteOptions(
    threads = 2,
    runLevel = CourgetteRunLevel.SCENARIO,
    rerunFailedScenarios = true,
    showTestOutput = true,
    reportTargetDir = "target",
    cucumberOptions = @CucumberOptions(
        features = "src/test/resources/features/",
            glue = "steps",
            plugin = {
                    "pretty",
                    "json:target/cucumber.json",
                    "html:target/cucumber"},
            strict = true
    ))

public class TestRunner2 {
}
```
When trying to run this class I get 'IncompatibleClassChangeError', with following stacktrace:
```
java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at cucumber.runtime.io.ResourceLoaderClassFinder.loadClass(ResourceLoaderClassFinder.java:38)
	at cucumber.runtime.io.ResourceLoaderClassFinder.getDescendants(ResourceLoaderClassFinder.java:26)
	at cucumber.runtime.Reflections.instantiateSubclasses(Reflections.java:28)
	at cucumber.runtime.Runtime.loadBackends(Runtime.java:99)
	at cucumber.runtime.Runtime.<init>(Runtime.java:66)
	at courgette.runtime.CourgetteFeatureLoader.createRuntime(CourgetteFeatureLoader.java:60)
	at courgette.runtime.CourgetteFeatureLoader.<init>(CourgetteFeatureLoader.java:30)
	at courgette.api.junit.Courgette.<init>(Courgette.java:36)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

Any ideas what I'm doing wrong?

**Comment by prashant-ramcharan** [comment]
Hello,

1. What version of Courgette and Java are you using?
2. Did you refresh the project dependancies?
3. Do you face the same issue with this project? https://github.com/prashant-ramcharan/courgette-jvm-example

**Comment by prashant-ramcharan** [comment]
Closing issue due to lack of information.

**Comment by basmussen** [comment]
I had the same issue with the version 2.4.3. After clean up the classpath and get this lib a higher prio the process came normally.
