### ISSUE TITLE
Integration with ReportPortal

### ISSUE THREAD

**Issue by whaque81** [prashant-ramcharan/courgette-jvm#78]
Hello Ram/Prashant,

Do you have any plans of integrating with http://reportportal.io/ for generating online dashboards?

-W

**Comment by prashant-ramcharan** [comment]
Hello,

Did you try adding the plugin to the Courgette runner? 

```java
@RunWith(Courgette.class)
@CourgetteOptions(
       ...
       cucumberOptions = @CucumberOptions(plugin = {"pretty", "com.epam.reportportal.cucumber.StepReporter"})
)
````

**Comment by whaque81** [comment]
I am using TestNG..

@Test
@CourgetteOptions(
        threads = 21,
        runLevel = CourgetteRunLevel.SCENARIO,
        rerunFailedScenarios = true,
        showTestOutput = true,
        reportTargetDir = "target",
        cucumberOptions = @CucumberOptions(
                features = "src/test/resources/features",
                glue = {"stepdefs"},
                tags = {"@tag"},
                plugin = {
                        "pretty",
                        "com.epam.reportportal.cucumber.ScenarioReporter"},
//                        "json:target/cucumber-report/cucumber.json",
//                        "html:target/cucumber-report/cucumber.html"},
                strict = true
        ))

It is giving me the following error...

initialize(com.onetrust.qa.suite.runners.TestRunner)  Time elapsed: 0.272 sec  <<< FAILURE!
java.lang.NoClassDefFoundError: gherkin/formatter/Formatter
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at cucumber.runtime.formatter.PluginFactory.loadClass(PluginFactory.java:174)
	at cucumber.runtime.formatter.PluginFactory.pluginClass(PluginFactory.java:166)
	at cucumber.runtime.formatter.PluginFactory.getPluginClass(PluginFactory.java:223)
	at cucumber.runtime.formatter.PluginFactory.isFormatterName(PluginFactory.java:201)
	at cucumber.runtime.RuntimeOptions$ParsedPluginData.addPluginName(RuntimeOptions.java:471)
	at cucumber.runtime.RuntimeOptions.parse(RuntimeOptions.java:157)
	at cucumber.runtime.RuntimeOptions.<init>(RuntimeOptions.java:115)
	at cucumber.runtime.RuntimeOptions.<init>(RuntimeOptions.java:108)
	at cucumber.runtime.RuntimeOptions.<init>(RuntimeOptions.java:100)
	at courgette.runtime.CourgetteFeatureLoader.createRuntimeOptions(CourgetteFeatureLoader.java:54)
	at courgette.runtime.CourgetteFeatureLoader.<init>(CourgetteFeatureLoader.java:29)
	at courgette.api.testng.TestNGCourgette.initialize(TestNGCourgette.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:170)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:104)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.ClassNotFoundException: gherkin.formatter.Formatter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 69 more

**Comment by prashant-ramcharan** [comment]
You need these files in your project + classpath.

https://github.com/reportportal/agent-java-cucumber/tree/master/src/main/java/com/epam/reportportal/cucumber

**Comment by prashant-ramcharan** [comment]
Unfortunately, there's no plans of integrating Courgette with ReportPortal if the above does not work.

**Comment by prashant-ramcharan** [comment]
Did the above work @whaque81 ?

**Comment by prashant-ramcharan** [comment]
Just an update on this.. will try to implement  this functionality in the next release of Courgette.
